//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace HsrOrderApp.UI.Silverlight.CustomerService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOBase", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.ResponseType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetOrderResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.DTOVersionObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.OrderDetailDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.AddressDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.DTOParentObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.ProductDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.CustomerDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.OrderDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.OrderListDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetProductResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetProductsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetCustomerResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.RequestType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetProductRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetProductsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetOrderRequest))]
    public partial class DTOBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseType", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Requests_" +
        "Responses.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetOrderResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetProductResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetProductsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetCustomerResponse))]
    public partial class ResponseType : HsrOrderApp.UI.Silverlight.CustomerService.DTOBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Requests_" +
        "Responses")]
    public partial class GetOrderResponse : HsrOrderApp.UI.Silverlight.CustomerService.ResponseType {
        
        private HsrOrderApp.UI.Silverlight.CustomerService.OrderDTO OrderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HsrOrderApp.UI.Silverlight.CustomerService.OrderDTO Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOVersionObject", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.OrderDetailDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.AddressDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.DTOParentObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.ProductDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.CustomerDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.OrderDTO))]
    public partial class DTOVersionObject : HsrOrderApp.UI.Silverlight.CustomerService.DTOBase {
        
        private ulong VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO")]
    public partial class OrderDetailDTO : HsrOrderApp.UI.Silverlight.CustomerService.DTOVersionObject {
        
        private int ProductIdField;
        
        private string ProductNameField;
        
        private int QuantityInUnitsField;
        
        private decimal UnitPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuantityInUnits {
            get {
                return this.QuantityInUnitsField;
            }
            set {
                if ((this.QuantityInUnitsField.Equals(value) != true)) {
                    this.QuantityInUnitsField = value;
                    this.RaisePropertyChanged("QuantityInUnits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressDTO", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO")]
    public partial class AddressDTO : HsrOrderApp.UI.Silverlight.CustomerService.DTOVersionObject {
        
        private string AddressLine1Field;
        
        private string AddressLine2Field;
        
        private string CityField;
        
        private string EmailField;
        
        private string PhoneField;
        
        private string PostalCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOParentObject", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.ProductDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.CustomerDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.OrderDTO))]
    public partial class DTOParentObject : HsrOrderApp.UI.Silverlight.CustomerService.DTOVersionObject {
        
        private System.Collections.ObjectModel.ObservableCollection<HsrOrderApp.UI.Silverlight.CustomerService.ChangeItem> ChangesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<HsrOrderApp.UI.Silverlight.CustomerService.ChangeItem> Changes {
            get {
                return this.ChangesField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangesField, value) != true)) {
                    this.ChangesField = value;
                    this.RaisePropertyChanged("Changes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTO", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO")]
    public partial class ProductDTO : HsrOrderApp.UI.Silverlight.CustomerService.DTOParentObject {
        
        private string CategoryField;
        
        private decimal ListUnitPriceField;
        
        private string NameField;
        
        private string ProductNumberField;
        
        private double QuantityPerUnitField;
        
        private int UnitsOnStockField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ListUnitPrice {
            get {
                return this.ListUnitPriceField;
            }
            set {
                if ((this.ListUnitPriceField.Equals(value) != true)) {
                    this.ListUnitPriceField = value;
                    this.RaisePropertyChanged("ListUnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductNumber {
            get {
                return this.ProductNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNumberField, value) != true)) {
                    this.ProductNumberField = value;
                    this.RaisePropertyChanged("ProductNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QuantityPerUnit {
            get {
                return this.QuantityPerUnitField;
            }
            set {
                if ((this.QuantityPerUnitField.Equals(value) != true)) {
                    this.QuantityPerUnitField = value;
                    this.RaisePropertyChanged("QuantityPerUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitsOnStock {
            get {
                return this.UnitsOnStockField;
            }
            set {
                if ((this.UnitsOnStockField.Equals(value) != true)) {
                    this.UnitsOnStockField = value;
                    this.RaisePropertyChanged("UnitsOnStock");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDTO", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO")]
    public partial class CustomerDTO : HsrOrderApp.UI.Silverlight.CustomerService.DTOParentObject {
        
        private System.Collections.ObjectModel.ObservableCollection<HsrOrderApp.UI.Silverlight.CustomerService.AddressDTO> AddressesField;
        
        private string FirstNameField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<HsrOrderApp.UI.Silverlight.CustomerService.AddressDTO> Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDTO", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO")]
    public partial class OrderDTO : HsrOrderApp.UI.Silverlight.CustomerService.DTOParentObject {
        
        private int CustomerIdField;
        
        private string CustomerNameField;
        
        private System.Collections.ObjectModel.ObservableCollection<HsrOrderApp.UI.Silverlight.CustomerService.OrderDetailDTO> DetailsField;
        
        private System.Nullable<System.DateTime> OrderDateField;
        
        private HsrOrderApp.UI.Silverlight.CustomerService.OrderStatus OrderStatusField;
        
        private System.Nullable<System.DateTime> ShippedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<HsrOrderApp.UI.Silverlight.CustomerService.OrderDetailDTO> Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HsrOrderApp.UI.Silverlight.CustomerService.OrderStatus OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((this.OrderStatusField.Equals(value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShippedDate {
            get {
                return this.ShippedDateField;
            }
            set {
                if ((this.ShippedDateField.Equals(value) != true)) {
                    this.ShippedDateField = value;
                    this.RaisePropertyChanged("ShippedDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrdersResponse", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Requests_" +
        "Responses")]
    public partial class GetOrdersResponse : HsrOrderApp.UI.Silverlight.CustomerService.ResponseType {
        
        private System.Collections.ObjectModel.ObservableCollection<HsrOrderApp.UI.Silverlight.CustomerService.OrderListDTO> OrdersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<HsrOrderApp.UI.Silverlight.CustomerService.OrderListDTO> Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderListDTO", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO")]
    public partial class OrderListDTO : HsrOrderApp.UI.Silverlight.CustomerService.DTOBase {
        
        private string CustomerNameField;
        
        private System.Nullable<System.DateTime> OrderDateField;
        
        private HsrOrderApp.UI.Silverlight.CustomerService.OrderStatus OrderStatusField;
        
        private System.Nullable<System.DateTime> ShippedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HsrOrderApp.UI.Silverlight.CustomerService.OrderStatus OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((this.OrderStatusField.Equals(value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShippedDate {
            get {
                return this.ShippedDateField;
            }
            set {
                if ((this.ShippedDateField.Equals(value) != true)) {
                    this.ShippedDateField = value;
                    this.RaisePropertyChanged("ShippedDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProductResponse", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Requests_" +
        "Responses")]
    public partial class GetProductResponse : HsrOrderApp.UI.Silverlight.CustomerService.ResponseType {
        
        private HsrOrderApp.UI.Silverlight.CustomerService.ProductDTO ProductField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HsrOrderApp.UI.Silverlight.CustomerService.ProductDTO Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProductsResponse", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Requests_" +
        "Responses")]
    public partial class GetProductsResponse : HsrOrderApp.UI.Silverlight.CustomerService.ResponseType {
        
        private System.Collections.ObjectModel.ObservableCollection<HsrOrderApp.UI.Silverlight.CustomerService.ProductDTO> ProductsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<HsrOrderApp.UI.Silverlight.CustomerService.ProductDTO> Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreCustomerResponse", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Requests_" +
        "Responses")]
    public partial class StoreCustomerResponse : HsrOrderApp.UI.Silverlight.CustomerService.ResponseType {
        
        private int CustomerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCustomerResponse", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Requests_" +
        "Responses")]
    public partial class GetCustomerResponse : HsrOrderApp.UI.Silverlight.CustomerService.ResponseType {
        
        private HsrOrderApp.UI.Silverlight.CustomerService.CustomerDTO CustomerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HsrOrderApp.UI.Silverlight.CustomerService.CustomerDTO Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestType", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Requests_" +
        "Responses.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetProductRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetProductsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.GetOrderRequest))]
    public partial class RequestType : HsrOrderApp.UI.Silverlight.CustomerService.DTOBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrdersRequest", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Requests_" +
        "Responses")]
    public partial class GetOrdersRequest : HsrOrderApp.UI.Silverlight.CustomerService.RequestType {
        
        private int CustomerIdField;
        
        private HsrOrderApp.UI.Silverlight.CustomerService.OrderSearchType SearchTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HsrOrderApp.UI.Silverlight.CustomerService.OrderSearchType SearchType {
            get {
                return this.SearchTypeField;
            }
            set {
                if ((this.SearchTypeField.Equals(value) != true)) {
                    this.SearchTypeField = value;
                    this.RaisePropertyChanged("SearchType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProductRequest", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Requests_" +
        "Responses")]
    public partial class GetProductRequest : HsrOrderApp.UI.Silverlight.CustomerService.RequestType {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProductsRequest", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Requests_" +
        "Responses")]
    public partial class GetProductsRequest : HsrOrderApp.UI.Silverlight.CustomerService.RequestType {
        
        private string CategoryField;
        
        private string ProductNameField;
        
        private HsrOrderApp.UI.Silverlight.CustomerService.ProductSearchType SearchTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HsrOrderApp.UI.Silverlight.CustomerService.ProductSearchType SearchType {
            get {
                return this.SearchTypeField;
            }
            set {
                if ((this.SearchTypeField.Equals(value) != true)) {
                    this.SearchTypeField = value;
                    this.RaisePropertyChanged("SearchType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreCustomerRequest", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Requests_" +
        "Responses")]
    public partial class StoreCustomerRequest : HsrOrderApp.UI.Silverlight.CustomerService.RequestType {
        
        private HsrOrderApp.UI.Silverlight.CustomerService.CustomerDTO CustomerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HsrOrderApp.UI.Silverlight.CustomerService.CustomerDTO Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Requests_" +
        "Responses")]
    public partial class GetOrderRequest : HsrOrderApp.UI.Silverlight.CustomerService.RequestType {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeItem", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.ChangeSet" +
        "")]
    public partial class ChangeItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HsrOrderApp.UI.Silverlight.CustomerService.ChangeType ChangeTypeField;
        
        private HsrOrderApp.UI.Silverlight.CustomerService.DTOVersionObject ObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HsrOrderApp.UI.Silverlight.CustomerService.ChangeType ChangeType {
            get {
                return this.ChangeTypeField;
            }
            set {
                if ((this.ChangeTypeField.Equals(value) != true)) {
                    this.ChangeTypeField = value;
                    this.RaisePropertyChanged("ChangeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HsrOrderApp.UI.Silverlight.CustomerService.DTOVersionObject Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatus", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.SharedEnums")]
    public enum OrderStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Draft = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ordered = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Shipped = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeType", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.SharedEnums")]
    public enum ChangeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChildUpate = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChildInsert = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChildDelete = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderSearchType", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.SharedEnums")]
    public enum OrderSearchType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByCustomer = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSearchType", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.SharedEnums")]
    public enum ProductSearchType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByCategory = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByName = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Faults")]
    public partial class ServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HsrOrderApp.UI.Silverlight.CustomerService.FaultType FaultTypeField;
        
        private System.Guid IdField;
        
        private string MessageTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HsrOrderApp.UI.Silverlight.CustomerService.FaultType FaultType {
            get {
                return this.FaultTypeField;
            }
            set {
                if ((this.FaultTypeField.Equals(value) != true)) {
                    this.FaultTypeField = value;
                    this.RaisePropertyChanged("FaultType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageText {
            get {
                return this.MessageTextField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTextField, value) != true)) {
                    this.MessageTextField = value;
                    this.RaisePropertyChanged("MessageText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultType", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Faults")]
    public enum FaultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        General = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Security = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Concurrency = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validation = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
    public partial class ValidationFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<HsrOrderApp.UI.Silverlight.CustomerService.ValidationDetail> DetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<HsrOrderApp.UI.Silverlight.CustomerService.ValidationDetail> Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationDetail", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Practices.EnterpriseLibrary.Val" +
        "idation.Integration.WCF")]
    public partial class ValidationDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string KeyField;
        
        private string MessageField;
        
        private string TagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag {
            get {
                return this.TagField;
            }
            set {
                if ((object.ReferenceEquals(this.TagField, value) != true)) {
                    this.TagField = value;
                    this.RaisePropertyChanged("Tag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ch.hsr.HsrOrderApp", ConfigurationName="CustomerService.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://ch.hsr.HsrOrderApp/ICustomerService/GetOrderById", ReplyAction="http://ch.hsr.HsrOrderApp/ICustomerService/GetOrderByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.ServiceFault), Action="http://ch.hsr.HsrOrderApp/ICustomerService/GetOrderByIdServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.ValidationFault), Action="http://ch.hsr.HsrOrderApp/ICustomerService/GetOrderByIdValidationFaultFault", Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
        System.IAsyncResult BeginGetOrderById(HsrOrderApp.UI.Silverlight.CustomerService.GetOrderRequest request, System.AsyncCallback callback, object asyncState);
        
        HsrOrderApp.UI.Silverlight.CustomerService.GetOrderResponse EndGetOrderById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://ch.hsr.HsrOrderApp/ICustomerService/GetOrdersByCriteria", ReplyAction="http://ch.hsr.HsrOrderApp/ICustomerService/GetOrdersByCriteriaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.ServiceFault), Action="http://ch.hsr.HsrOrderApp/ICustomerService/GetOrdersByCriteriaServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Faults")]
        System.IAsyncResult BeginGetOrdersByCriteria(HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersRequest request, System.AsyncCallback callback, object asyncState);
        
        HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersResponse EndGetOrdersByCriteria(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://ch.hsr.HsrOrderApp/ICustomerService/GetProductById", ReplyAction="http://ch.hsr.HsrOrderApp/ICustomerService/GetProductByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.ServiceFault), Action="http://ch.hsr.HsrOrderApp/ICustomerService/GetProductByIdServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Faults")]
        System.IAsyncResult BeginGetProductById(HsrOrderApp.UI.Silverlight.CustomerService.GetProductRequest request, System.AsyncCallback callback, object asyncState);
        
        HsrOrderApp.UI.Silverlight.CustomerService.GetProductResponse EndGetProductById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://ch.hsr.HsrOrderApp/ICustomerService/GetProductByCriteria", ReplyAction="http://ch.hsr.HsrOrderApp/ICustomerService/GetProductByCriteriaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.ServiceFault), Action="http://ch.hsr.HsrOrderApp/ICustomerService/GetProductByCriteriaServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Faults")]
        System.IAsyncResult BeginGetProductByCriteria(HsrOrderApp.UI.Silverlight.CustomerService.GetProductsRequest request, System.AsyncCallback callback, object asyncState);
        
        HsrOrderApp.UI.Silverlight.CustomerService.GetProductsResponse EndGetProductByCriteria(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://ch.hsr.HsrOrderApp/ICustomerService/StoreCustomer", ReplyAction="http://ch.hsr.HsrOrderApp/ICustomerService/StoreCustomerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.ServiceFault), Action="http://ch.hsr.HsrOrderApp/ICustomerService/StoreCustomerServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Faults")]
        System.IAsyncResult BeginStoreCustomer(HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerRequest request, System.AsyncCallback callback, object asyncState);
        
        HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerResponse EndStoreCustomer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://ch.hsr.HsrOrderApp/ICustomerService/GetCustomer", ReplyAction="http://ch.hsr.HsrOrderApp/ICustomerService/GetCustomerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HsrOrderApp.UI.Silverlight.CustomerService.ServiceFault), Action="http://ch.hsr.HsrOrderApp/ICustomerService/GetCustomerServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/HsrOrderApp.SharedLibraries.DTO.Faults")]
        System.IAsyncResult BeginGetCustomer(System.AsyncCallback callback, object asyncState);
        
        HsrOrderApp.UI.Silverlight.CustomerService.GetCustomerResponse EndGetCustomer(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOrderByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOrderByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HsrOrderApp.UI.Silverlight.CustomerService.GetOrderResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HsrOrderApp.UI.Silverlight.CustomerService.GetOrderResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOrdersByCriteriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOrdersByCriteriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProductByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HsrOrderApp.UI.Silverlight.CustomerService.GetProductResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HsrOrderApp.UI.Silverlight.CustomerService.GetProductResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProductByCriteriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductByCriteriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HsrOrderApp.UI.Silverlight.CustomerService.GetProductsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HsrOrderApp.UI.Silverlight.CustomerService.GetProductsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public StoreCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HsrOrderApp.UI.Silverlight.CustomerService.GetCustomerResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HsrOrderApp.UI.Silverlight.CustomerService.GetCustomerResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService>, HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService {
        
        private BeginOperationDelegate onBeginGetOrderByIdDelegate;
        
        private EndOperationDelegate onEndGetOrderByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetOrderByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetOrdersByCriteriaDelegate;
        
        private EndOperationDelegate onEndGetOrdersByCriteriaDelegate;
        
        private System.Threading.SendOrPostCallback onGetOrdersByCriteriaCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProductByIdDelegate;
        
        private EndOperationDelegate onEndGetProductByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProductByCriteriaDelegate;
        
        private EndOperationDelegate onEndGetProductByCriteriaDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductByCriteriaCompletedDelegate;
        
        private BeginOperationDelegate onBeginStoreCustomerDelegate;
        
        private EndOperationDelegate onEndStoreCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onStoreCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCustomerDelegate;
        
        private EndOperationDelegate onEndGetCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onGetCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetOrderByIdCompletedEventArgs> GetOrderByIdCompleted;
        
        public event System.EventHandler<GetOrdersByCriteriaCompletedEventArgs> GetOrdersByCriteriaCompleted;
        
        public event System.EventHandler<GetProductByIdCompletedEventArgs> GetProductByIdCompleted;
        
        public event System.EventHandler<GetProductByCriteriaCompletedEventArgs> GetProductByCriteriaCompleted;
        
        public event System.EventHandler<StoreCustomerCompletedEventArgs> StoreCustomerCompleted;
        
        public event System.EventHandler<GetCustomerCompletedEventArgs> GetCustomerCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService.BeginGetOrderById(HsrOrderApp.UI.Silverlight.CustomerService.GetOrderRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOrderById(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HsrOrderApp.UI.Silverlight.CustomerService.GetOrderResponse HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService.EndGetOrderById(System.IAsyncResult result) {
            return base.Channel.EndGetOrderById(result);
        }
        
        private System.IAsyncResult OnBeginGetOrderById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HsrOrderApp.UI.Silverlight.CustomerService.GetOrderRequest request = ((HsrOrderApp.UI.Silverlight.CustomerService.GetOrderRequest)(inValues[0]));
            return ((HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService)(this)).BeginGetOrderById(request, callback, asyncState);
        }
        
        private object[] OnEndGetOrderById(System.IAsyncResult result) {
            HsrOrderApp.UI.Silverlight.CustomerService.GetOrderResponse retVal = ((HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService)(this)).EndGetOrderById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOrderByIdCompleted(object state) {
            if ((this.GetOrderByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOrderByIdCompleted(this, new GetOrderByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOrderByIdAsync(HsrOrderApp.UI.Silverlight.CustomerService.GetOrderRequest request) {
            this.GetOrderByIdAsync(request, null);
        }
        
        public void GetOrderByIdAsync(HsrOrderApp.UI.Silverlight.CustomerService.GetOrderRequest request, object userState) {
            if ((this.onBeginGetOrderByIdDelegate == null)) {
                this.onBeginGetOrderByIdDelegate = new BeginOperationDelegate(this.OnBeginGetOrderById);
            }
            if ((this.onEndGetOrderByIdDelegate == null)) {
                this.onEndGetOrderByIdDelegate = new EndOperationDelegate(this.OnEndGetOrderById);
            }
            if ((this.onGetOrderByIdCompletedDelegate == null)) {
                this.onGetOrderByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOrderByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetOrderByIdDelegate, new object[] {
                        request}, this.onEndGetOrderByIdDelegate, this.onGetOrderByIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService.BeginGetOrdersByCriteria(HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOrdersByCriteria(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersResponse HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService.EndGetOrdersByCriteria(System.IAsyncResult result) {
            return base.Channel.EndGetOrdersByCriteria(result);
        }
        
        private System.IAsyncResult OnBeginGetOrdersByCriteria(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersRequest request = ((HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersRequest)(inValues[0]));
            return ((HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService)(this)).BeginGetOrdersByCriteria(request, callback, asyncState);
        }
        
        private object[] OnEndGetOrdersByCriteria(System.IAsyncResult result) {
            HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersResponse retVal = ((HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService)(this)).EndGetOrdersByCriteria(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOrdersByCriteriaCompleted(object state) {
            if ((this.GetOrdersByCriteriaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOrdersByCriteriaCompleted(this, new GetOrdersByCriteriaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOrdersByCriteriaAsync(HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersRequest request) {
            this.GetOrdersByCriteriaAsync(request, null);
        }
        
        public void GetOrdersByCriteriaAsync(HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersRequest request, object userState) {
            if ((this.onBeginGetOrdersByCriteriaDelegate == null)) {
                this.onBeginGetOrdersByCriteriaDelegate = new BeginOperationDelegate(this.OnBeginGetOrdersByCriteria);
            }
            if ((this.onEndGetOrdersByCriteriaDelegate == null)) {
                this.onEndGetOrdersByCriteriaDelegate = new EndOperationDelegate(this.OnEndGetOrdersByCriteria);
            }
            if ((this.onGetOrdersByCriteriaCompletedDelegate == null)) {
                this.onGetOrdersByCriteriaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOrdersByCriteriaCompleted);
            }
            base.InvokeAsync(this.onBeginGetOrdersByCriteriaDelegate, new object[] {
                        request}, this.onEndGetOrdersByCriteriaDelegate, this.onGetOrdersByCriteriaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService.BeginGetProductById(HsrOrderApp.UI.Silverlight.CustomerService.GetProductRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductById(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HsrOrderApp.UI.Silverlight.CustomerService.GetProductResponse HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService.EndGetProductById(System.IAsyncResult result) {
            return base.Channel.EndGetProductById(result);
        }
        
        private System.IAsyncResult OnBeginGetProductById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HsrOrderApp.UI.Silverlight.CustomerService.GetProductRequest request = ((HsrOrderApp.UI.Silverlight.CustomerService.GetProductRequest)(inValues[0]));
            return ((HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService)(this)).BeginGetProductById(request, callback, asyncState);
        }
        
        private object[] OnEndGetProductById(System.IAsyncResult result) {
            HsrOrderApp.UI.Silverlight.CustomerService.GetProductResponse retVal = ((HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService)(this)).EndGetProductById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductByIdCompleted(object state) {
            if ((this.GetProductByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductByIdCompleted(this, new GetProductByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductByIdAsync(HsrOrderApp.UI.Silverlight.CustomerService.GetProductRequest request) {
            this.GetProductByIdAsync(request, null);
        }
        
        public void GetProductByIdAsync(HsrOrderApp.UI.Silverlight.CustomerService.GetProductRequest request, object userState) {
            if ((this.onBeginGetProductByIdDelegate == null)) {
                this.onBeginGetProductByIdDelegate = new BeginOperationDelegate(this.OnBeginGetProductById);
            }
            if ((this.onEndGetProductByIdDelegate == null)) {
                this.onEndGetProductByIdDelegate = new EndOperationDelegate(this.OnEndGetProductById);
            }
            if ((this.onGetProductByIdCompletedDelegate == null)) {
                this.onGetProductByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductByIdDelegate, new object[] {
                        request}, this.onEndGetProductByIdDelegate, this.onGetProductByIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService.BeginGetProductByCriteria(HsrOrderApp.UI.Silverlight.CustomerService.GetProductsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductByCriteria(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HsrOrderApp.UI.Silverlight.CustomerService.GetProductsResponse HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService.EndGetProductByCriteria(System.IAsyncResult result) {
            return base.Channel.EndGetProductByCriteria(result);
        }
        
        private System.IAsyncResult OnBeginGetProductByCriteria(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HsrOrderApp.UI.Silverlight.CustomerService.GetProductsRequest request = ((HsrOrderApp.UI.Silverlight.CustomerService.GetProductsRequest)(inValues[0]));
            return ((HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService)(this)).BeginGetProductByCriteria(request, callback, asyncState);
        }
        
        private object[] OnEndGetProductByCriteria(System.IAsyncResult result) {
            HsrOrderApp.UI.Silverlight.CustomerService.GetProductsResponse retVal = ((HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService)(this)).EndGetProductByCriteria(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductByCriteriaCompleted(object state) {
            if ((this.GetProductByCriteriaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductByCriteriaCompleted(this, new GetProductByCriteriaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductByCriteriaAsync(HsrOrderApp.UI.Silverlight.CustomerService.GetProductsRequest request) {
            this.GetProductByCriteriaAsync(request, null);
        }
        
        public void GetProductByCriteriaAsync(HsrOrderApp.UI.Silverlight.CustomerService.GetProductsRequest request, object userState) {
            if ((this.onBeginGetProductByCriteriaDelegate == null)) {
                this.onBeginGetProductByCriteriaDelegate = new BeginOperationDelegate(this.OnBeginGetProductByCriteria);
            }
            if ((this.onEndGetProductByCriteriaDelegate == null)) {
                this.onEndGetProductByCriteriaDelegate = new EndOperationDelegate(this.OnEndGetProductByCriteria);
            }
            if ((this.onGetProductByCriteriaCompletedDelegate == null)) {
                this.onGetProductByCriteriaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductByCriteriaCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductByCriteriaDelegate, new object[] {
                        request}, this.onEndGetProductByCriteriaDelegate, this.onGetProductByCriteriaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService.BeginStoreCustomer(HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginStoreCustomer(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerResponse HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService.EndStoreCustomer(System.IAsyncResult result) {
            return base.Channel.EndStoreCustomer(result);
        }
        
        private System.IAsyncResult OnBeginStoreCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerRequest request = ((HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerRequest)(inValues[0]));
            return ((HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService)(this)).BeginStoreCustomer(request, callback, asyncState);
        }
        
        private object[] OnEndStoreCustomer(System.IAsyncResult result) {
            HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerResponse retVal = ((HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService)(this)).EndStoreCustomer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnStoreCustomerCompleted(object state) {
            if ((this.StoreCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.StoreCustomerCompleted(this, new StoreCustomerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void StoreCustomerAsync(HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerRequest request) {
            this.StoreCustomerAsync(request, null);
        }
        
        public void StoreCustomerAsync(HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerRequest request, object userState) {
            if ((this.onBeginStoreCustomerDelegate == null)) {
                this.onBeginStoreCustomerDelegate = new BeginOperationDelegate(this.OnBeginStoreCustomer);
            }
            if ((this.onEndStoreCustomerDelegate == null)) {
                this.onEndStoreCustomerDelegate = new EndOperationDelegate(this.OnEndStoreCustomer);
            }
            if ((this.onStoreCustomerCompletedDelegate == null)) {
                this.onStoreCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnStoreCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginStoreCustomerDelegate, new object[] {
                        request}, this.onEndStoreCustomerDelegate, this.onStoreCustomerCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService.BeginGetCustomer(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCustomer(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HsrOrderApp.UI.Silverlight.CustomerService.GetCustomerResponse HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService.EndGetCustomer(System.IAsyncResult result) {
            return base.Channel.EndGetCustomer(result);
        }
        
        private System.IAsyncResult OnBeginGetCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService)(this)).BeginGetCustomer(callback, asyncState);
        }
        
        private object[] OnEndGetCustomer(System.IAsyncResult result) {
            HsrOrderApp.UI.Silverlight.CustomerService.GetCustomerResponse retVal = ((HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService)(this)).EndGetCustomer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCustomerCompleted(object state) {
            if ((this.GetCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCustomerCompleted(this, new GetCustomerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCustomerAsync() {
            this.GetCustomerAsync(null);
        }
        
        public void GetCustomerAsync(object userState) {
            if ((this.onBeginGetCustomerDelegate == null)) {
                this.onBeginGetCustomerDelegate = new BeginOperationDelegate(this.OnBeginGetCustomer);
            }
            if ((this.onEndGetCustomerDelegate == null)) {
                this.onEndGetCustomerDelegate = new EndOperationDelegate(this.OnEndGetCustomer);
            }
            if ((this.onGetCustomerCompletedDelegate == null)) {
                this.onGetCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginGetCustomerDelegate, null, this.onEndGetCustomerDelegate, this.onGetCustomerCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService CreateChannel() {
            return new CustomerServiceClientChannel(this);
        }
        
        private class CustomerServiceClientChannel : ChannelBase<HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService>, HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService {
            
            public CustomerServiceClientChannel(System.ServiceModel.ClientBase<HsrOrderApp.UI.Silverlight.CustomerService.ICustomerService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetOrderById(HsrOrderApp.UI.Silverlight.CustomerService.GetOrderRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetOrderById", _args, callback, asyncState);
                return _result;
            }
            
            public HsrOrderApp.UI.Silverlight.CustomerService.GetOrderResponse EndGetOrderById(System.IAsyncResult result) {
                object[] _args = new object[0];
                HsrOrderApp.UI.Silverlight.CustomerService.GetOrderResponse _result = ((HsrOrderApp.UI.Silverlight.CustomerService.GetOrderResponse)(base.EndInvoke("GetOrderById", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetOrdersByCriteria(HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetOrdersByCriteria", _args, callback, asyncState);
                return _result;
            }
            
            public HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersResponse EndGetOrdersByCriteria(System.IAsyncResult result) {
                object[] _args = new object[0];
                HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersResponse _result = ((HsrOrderApp.UI.Silverlight.CustomerService.GetOrdersResponse)(base.EndInvoke("GetOrdersByCriteria", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProductById(HsrOrderApp.UI.Silverlight.CustomerService.GetProductRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetProductById", _args, callback, asyncState);
                return _result;
            }
            
            public HsrOrderApp.UI.Silverlight.CustomerService.GetProductResponse EndGetProductById(System.IAsyncResult result) {
                object[] _args = new object[0];
                HsrOrderApp.UI.Silverlight.CustomerService.GetProductResponse _result = ((HsrOrderApp.UI.Silverlight.CustomerService.GetProductResponse)(base.EndInvoke("GetProductById", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProductByCriteria(HsrOrderApp.UI.Silverlight.CustomerService.GetProductsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetProductByCriteria", _args, callback, asyncState);
                return _result;
            }
            
            public HsrOrderApp.UI.Silverlight.CustomerService.GetProductsResponse EndGetProductByCriteria(System.IAsyncResult result) {
                object[] _args = new object[0];
                HsrOrderApp.UI.Silverlight.CustomerService.GetProductsResponse _result = ((HsrOrderApp.UI.Silverlight.CustomerService.GetProductsResponse)(base.EndInvoke("GetProductByCriteria", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginStoreCustomer(HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("StoreCustomer", _args, callback, asyncState);
                return _result;
            }
            
            public HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerResponse EndStoreCustomer(System.IAsyncResult result) {
                object[] _args = new object[0];
                HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerResponse _result = ((HsrOrderApp.UI.Silverlight.CustomerService.StoreCustomerResponse)(base.EndInvoke("StoreCustomer", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCustomer(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetCustomer", _args, callback, asyncState);
                return _result;
            }
            
            public HsrOrderApp.UI.Silverlight.CustomerService.GetCustomerResponse EndGetCustomer(System.IAsyncResult result) {
                object[] _args = new object[0];
                HsrOrderApp.UI.Silverlight.CustomerService.GetCustomerResponse _result = ((HsrOrderApp.UI.Silverlight.CustomerService.GetCustomerResponse)(base.EndInvoke("GetCustomer", _args, result)));
                return _result;
            }
        }
    }
}
