//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsrOrderApp.UI.Silverlight.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HsrOrderApp.UI.Silverlight.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strasse.
        /// </summary>
        public static string AddressDetailView_AddressLine1 {
            get {
                return ResourceManager.GetString("AddressDetailView_AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresszusatz.
        /// </summary>
        public static string AddressDetailView_AddressLine2 {
            get {
                return ResourceManager.GetString("AddressDetailView_AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stadt.
        /// </summary>
        public static string AddressDetailView_City {
            get {
                return ResourceManager.GetString("AddressDetailView_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string AddressDetailView_Email {
            get {
                return ResourceManager.GetString("AddressDetailView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string AddressDetailView_Telephone {
            get {
                return ResourceManager.GetString("AddressDetailView_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresse bearbeiten.
        /// </summary>
        public static string AddressDetailView_Title {
            get {
                return ResourceManager.GetString("AddressDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLZ.
        /// </summary>
        public static string AddressDetailView_ZIP {
            get {
                return ResourceManager.GetString("AddressDetailView_ZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresse bearbeiten.
        /// </summary>
        public static string AddressDetailViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AddressDetailViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchschnittliche Vorlaufzeit.
        /// </summary>
        public static string ConditionDetailView_AverageLeadTime {
            get {
                return ResourceManager.GetString("ConditionDetailView_AverageLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnungsbetrag des letzten Wareneingang.
        /// </summary>
        public static string ConditionDetailView_LastReceiptCost {
            get {
                return ResourceManager.GetString("ConditionDetailView_LastReceiptCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum des letzten Wareneingang.
        /// </summary>
        public static string ConditionDetailView_LastReceiptDate {
            get {
                return ResourceManager.GetString("ConditionDetailView_LastReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximale Bestellmenge.
        /// </summary>
        public static string ConditionDetailView_MaxOrderQuantity {
            get {
                return ResourceManager.GetString("ConditionDetailView_MaxOrderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimale Bestellmenge.
        /// </summary>
        public static string ConditionDetailView_MinOrderQuantity {
            get {
                return ResourceManager.GetString("ConditionDetailView_MinOrderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        public static string ConditionDetailView_Product {
            get {
                return ResourceManager.GetString("ConditionDetailView_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardpreis.
        /// </summary>
        public static string ConditionDetailView_StandardPrice {
            get {
                return ResourceManager.GetString("ConditionDetailView_StandardPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferantenkondition.
        /// </summary>
        public static string ConditionDetailView_Title {
            get {
                return ResourceManager.GetString("ConditionDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konditionen bearbeiten.
        /// </summary>
        public static string ConditionDetailViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ConditionDetailViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überdurchschnittlich.
        /// </summary>
        public static string CreditRating_AboveAverage {
            get {
                return ResourceManager.GetString("CreditRating_AboveAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchschnittlich.
        /// </summary>
        public static string CreditRating_Average {
            get {
                return ResourceManager.GetString("CreditRating_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterdurchschnittlich.
        /// </summary>
        public static string CreditRating_BelowAverage {
            get {
                return ResourceManager.GetString("CreditRating_BelowAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgezeichnet.
        /// </summary>
        public static string CreditRating_Excellent {
            get {
                return ResourceManager.GetString("CreditRating_Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior.
        /// </summary>
        public static string CreditRating_Superior {
            get {
                return ResourceManager.GetString("CreditRating_Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.00290039.
        /// </summary>
        public static string CurrencyFactor {
            get {
                return ResourceManager.GetString("CurrencyFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string CustomerDetailView_FirstName {
            get {
                return ResourceManager.GetString("CustomerDetailView_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string CustomerDetailView_Name {
            get {
                return ResourceManager.GetString("CustomerDetailView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adressen.
        /// </summary>
        public static string CustomerDetailView_Subtitle {
            get {
                return ResourceManager.GetString("CustomerDetailView_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde.
        /// </summary>
        public static string CustomerDetailView_Title {
            get {
                return ResourceManager.GetString("CustomerDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde bearbeiten.
        /// </summary>
        public static string CustomerDetailViewModel_DisplayName {
            get {
                return ResourceManager.GetString("CustomerDetailViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwalten Sie die Kunden..
        /// </summary>
        public static string CustomerView_Description {
            get {
                return ResourceManager.GetString("CustomerView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundenverwaltung.
        /// </summary>
        public static string CustomerView_DisplayName {
            get {
                return ResourceManager.GetString("CustomerView_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundenname.
        /// </summary>
        public static string CustomerView_Name {
            get {
                return ResourceManager.GetString("CustomerView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl offene Bestellungen.
        /// </summary>
        public static string CustomerView_OpenOrders {
            get {
                return ResourceManager.GetString("CustomerView_OpenOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Bestellungen total.
        /// </summary>
        public static string CustomerView_TotalOrders {
            get {
                return ResourceManager.GetString("CustomerView_TotalOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundenverwaltung.
        /// </summary>
        public static string CustomerViewModel_DisplayName {
            get {
                return ResourceManager.GetString("CustomerViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string DeleteCommand {
            get {
                return ResourceManager.GetString("DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Tage.
        /// </summary>
        public static string DeliveryTimeFromStock_Plural {
            get {
                return ResourceManager.GetString("DeliveryTimeFromStock_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Tag.
        /// </summary>
        public static string DeliveryTimeFromStock_Singular {
            get {
                return ResourceManager.GetString("DeliveryTimeFromStock_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf Anfrage.
        /// </summary>
        public static string DeliveryTimeFromStock_Unknown {
            get {
                return ResourceManager.GetString("DeliveryTimeFromStock_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string DetailDialog_Cancel {
            get {
                return ResourceManager.GetString("DetailDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string DetailDialog_OK {
            get {
                return ResourceManager.GetString("DetailDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string EditCommand {
            get {
                return ResourceManager.GetString("EditCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laden.
        /// </summary>
        public static string LoadCommand {
            get {
                return ResourceManager.GetString("LoadCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundenverwaltung.
        /// </summary>
        public static string MainWindow_hlkCustomer {
            get {
                return ResourceManager.GetString("MainWindow_hlkCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DE.
        /// </summary>
        public static string MainWindow_hlkDE {
            get {
                return ResourceManager.GetString("MainWindow_hlkDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string MainWindow_hlkEN {
            get {
                return ResourceManager.GetString("MainWindow_hlkEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellverwaltung.
        /// </summary>
        public static string MainWindow_hlkOrder {
            get {
                return ResourceManager.GetString("MainWindow_hlkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktverwaltung.
        /// </summary>
        public static string MainWindow_hlkProduct {
            get {
                return ResourceManager.GetString("MainWindow_hlkProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerverwaltung.
        /// </summary>
        public static string MainWindow_hlkUser {
            get {
                return ResourceManager.GetString("MainWindow_hlkUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        public static string NewCommand {
            get {
                return ResourceManager.GetString("NewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Lager ({0} Einheiten).
        /// </summary>
        public static string OnStock {
            get {
                return ResourceManager.GetString("OnStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erwartete Lieferfrist.
        /// </summary>
        public static string OrderDetailDetailView_DeliveryTime {
            get {
                return ResourceManager.GetString("OrderDetailDetailView_DeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis pro Einheit.
        /// </summary>
        public static string OrderDetailDetailView_Price {
            get {
                return ResourceManager.GetString("OrderDetailDetailView_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        public static string OrderDetailDetailView_Product {
            get {
                return ResourceManager.GetString("OrderDetailDetailView_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menge.
        /// </summary>
        public static string OrderDetailDetailView_Quantity {
            get {
                return ResourceManager.GetString("OrderDetailDetailView_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellposition.
        /// </summary>
        public static string OrderDetailDetailView_Title {
            get {
                return ResourceManager.GetString("OrderDetailDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totalbetrag.
        /// </summary>
        public static string OrderDetailDetailView_TotalPrice {
            get {
                return ResourceManager.GetString("OrderDetailDetailView_TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde.
        /// </summary>
        public static string OrderDetailView_Customer {
            get {
                return ResourceManager.GetString("OrderDetailView_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum der Bestellung.
        /// </summary>
        public static string OrderDetailView_DateOfOrder {
            get {
                return ResourceManager.GetString("OrderDetailView_DateOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum der Lieferung.
        /// </summary>
        public static string OrderDetailView_DateOfShipment {
            get {
                return ResourceManager.GetString("OrderDetailView_DateOfShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string OrderDetailView_Status {
            get {
                return ResourceManager.GetString("OrderDetailView_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellpositionen.
        /// </summary>
        public static string OrderDetailView_SubtitleOrderDetail {
            get {
                return ResourceManager.GetString("OrderDetailView_SubtitleOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellung.
        /// </summary>
        public static string OrderDetailView_Title {
            get {
                return ResourceManager.GetString("OrderDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellung bearbeiten.
        /// </summary>
        public static string OrderDetailViewModel_DisplayName {
            get {
                return ResourceManager.GetString("OrderDetailViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellposition bearbeiten.
        /// </summary>
        public static string OrderItemDetailViewModel_DisplayName {
            get {
                return ResourceManager.GetString("OrderItemDetailViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entwurf.
        /// </summary>
        public static string OrderStatus_Draft {
            get {
                return ResourceManager.GetString("OrderStatus_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellt.
        /// </summary>
        public static string OrderStatus_Ordered {
            get {
                return ResourceManager.GetString("OrderStatus_Ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geliefert.
        /// </summary>
        public static string OrderStatus_Shipped {
            get {
                return ResourceManager.GetString("OrderStatus_Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde.
        /// </summary>
        public static string OrderView_Customer {
            get {
                return ResourceManager.GetString("OrderView_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum der Lieferung.
        /// </summary>
        public static string OrderView_DateShipment {
            get {
                return ResourceManager.GetString("OrderView_DateShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten Sie die Bestellungen.
        /// </summary>
        public static string OrderView_Decription {
            get {
                return ResourceManager.GetString("OrderView_Decription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Nr..
        /// </summary>
        public static string OrderView_Id {
            get {
                return ResourceManager.GetString("OrderView_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum der Bestellung.
        /// </summary>
        public static string OrderView_OrderDate {
            get {
                return ResourceManager.GetString("OrderView_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totalbetrag.
        /// </summary>
        public static string OrderView_Price {
            get {
                return ResourceManager.GetString("OrderView_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string OrderView_Status {
            get {
                return ResourceManager.GetString("OrderView_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellverwaltung.
        /// </summary>
        public static string OrderView_Title {
            get {
                return ResourceManager.GetString("OrderView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellverwaltung.
        /// </summary>
        public static string OrderViewModel_DisplayName {
            get {
                return ResourceManager.GetString("OrderViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string ProductDetailView_Category {
            get {
                return ResourceManager.GetString("ProductDetailView_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erwartete Lieferzeit des Lieferanten.
        /// </summary>
        public static string ProductDetailView_DeliveryTimeWhenNotOnStock {
            get {
                return ResourceManager.GetString("ProductDetailView_DeliveryTimeWhenNotOnStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis pro Einheit.
        /// </summary>
        public static string ProductDetailView_PricePerUnit {
            get {
                return ResourceManager.GetString("ProductDetailView_PricePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktname.
        /// </summary>
        public static string ProductDetailView_ProductName {
            get {
                return ResourceManager.GetString("ProductDetailView_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nummer.
        /// </summary>
        public static string ProductDetailView_ProductNumber {
            get {
                return ResourceManager.GetString("ProductDetailView_ProductNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menge pro Einheit.
        /// </summary>
        public static string ProductDetailView_QuantityPerUnit {
            get {
                return ResourceManager.GetString("ProductDetailView_QuantityPerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        public static string ProductDetailView_Title {
            get {
                return ResourceManager.GetString("ProductDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagerbestand.
        /// </summary>
        public static string ProductDetailView_UnitsOnStock {
            get {
                return ResourceManager.GetString("ProductDetailView_UnitsOnStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt bearbeiten.
        /// </summary>
        public static string ProductDetailViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ProductDetailViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten Sie die Produkte.
        /// </summary>
        public static string ProductView_Decription {
            get {
                return ResourceManager.GetString("ProductView_Decription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktverwaltung.
        /// </summary>
        public static string ProductView_Title {
            get {
                return ResourceManager.GetString("ProductView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktverwaltung.
        /// </summary>
        public static string ProductViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ProductViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle.
        /// </summary>
        public static string RoleDetailView_Role {
            get {
                return ResourceManager.GetString("RoleDetailView_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle auswählen.
        /// </summary>
        public static string RoleDetailView_Title {
            get {
                return ResourceManager.GetString("RoleDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle auswählen.
        /// </summary>
        public static string RoleDetailViewModel_DisplayName {
            get {
                return ResourceManager.GetString("RoleDetailViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string SaveCommand {
            get {
                return ResourceManager.GetString("SaveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde.
        /// </summary>
        public static string UserDetailView_Customer {
            get {
                return ResourceManager.GetString("UserDetailView_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string UserDetailView_Password {
            get {
                return ResourceManager.GetString("UserDetailView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle.
        /// </summary>
        public static string UserDetailView_Rolename {
            get {
                return ResourceManager.GetString("UserDetailView_Rolename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollen.
        /// </summary>
        public static string UserDetailView_Subtitle_Roles {
            get {
                return ResourceManager.GetString("UserDetailView_Subtitle_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer.
        /// </summary>
        public static string UserDetailView_Title {
            get {
                return ResourceManager.GetString("UserDetailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername.
        /// </summary>
        public static string UserDetailView_UserName {
            get {
                return ResourceManager.GetString("UserDetailView_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer bearbeiten.
        /// </summary>
        public static string UserDetailViewModel_DisplayName {
            get {
                return ResourceManager.GetString("UserDetailViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten Sie die Benutzer.
        /// </summary>
        public static string UserView_Decription {
            get {
                return ResourceManager.GetString("UserView_Decription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollen.
        /// </summary>
        public static string UserView_Roles {
            get {
                return ResourceManager.GetString("UserView_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerverwaltung.
        /// </summary>
        public static string UserView_Title {
            get {
                return ResourceManager.GetString("UserView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerverwaltung.
        /// </summary>
        public static string UserViewModel_DisplayName {
            get {
                return ResourceManager.GetString("UserViewModel_DisplayName", resourceCulture);
            }
        }
    }
}
